#!/bin/sh

EMAIL=2017jhoughto@tjhsst.edu

if [ "$1" = "James" ] && [ "$2" = "Houghton" ]
then
	echo "What would you like to blame on James Houghton?"
	read RESPONSE
	echo "Please type your name"
	read NAME
	echo "Please type your email"
	read FROM
	echo "$RESPONSE" | mailx -s "Blame on $(date)" -r "$NAME<$FROM>" $EMAIL
else
#	for NAME in "$@"
#	do
#		echo -n "$NAME "
#	done
	if [ -z "$@" ];
	then
		echo "no arguments xd"
		exit 1
	fi
	echo "$@ is not to blame"
fi
