#!/bin/sh

EMAIL=2017jhoughto@tjhsst.edu

shopt -s nocasematch

if [[ "$1" =~ "James" ]] && [[ "$2" =~ "Houghton" ]]
then
	echo "What would you like to blame on James Houghton?"
	read response
	echo -n "Please type your name: "
	read name
	echo -n "Please type your email: "
	read from
	echo -e "$response" | mailx -s "Blame on $(date) by $name" -r "$name<$from>" $EMAIL
else
	if [ -z "$@" ];
	then
		echo "no arguments xd"
		exit 2
	fi
	echo "Error: $@ is not to blame"
	exit 1
fi
