#!/bin/sh

EMAIL=2017jhoughto@tjhsst.edu

shopt -s nocasematch

if [[ "$1" =~ "James" ]] && [[ "$2" =~ "Houghton" ]]
then
	echo "What would you like to blame on James Houghton?"
	read RESPONSE
	echo -n "Please type your name: "
	read NAME
	echo -n "Please type your email: "
	read FROM
	echo "$RESPONSE" | mailx -s "Blame on $(date)" -r "$NAME<$FROM>" $EMAIL
else
	if [ -z "$@" ];
	then
		echo "no arguments xd"
		exit 2
	fi
	echo "Error: $@ is not to blame"
	exit 1
fi
